### ISSUE TITLE
Recognition state is getting reset

### ISSUE THREAD

**Issue by samirpramanik** [BlinkID/blinkid-ui-android#41]
Hi,

We are using Blink ID 4.8.0 for UAE ID card recognition. Once we scan the first side, we proceed to scanning the back side of the ID. But sometimes of there is significant glare on the screen, we are prompted with the glare warning text and then the recognition resets to the first side again. The message comes as - Please scan the front side of the selected document or choose another. Ideally it should not reset if back scanning is having issues.

Thanks!

**Comment by samirpramanik** [comment]
This is reproducible even on the app published on google play store. Sometimes, the message changes to - 

> Scan back side

, but denies to scan back side and recognizes only the front side again.

**Comment by matvidako** [comment]
Hi,

thanks for reporting the issue.

Does this happen only when glare is detected or also if it just takes too long to scan?

**Comment by samirpramanik** [comment]
For my case, it was taking too long to scan because of glare. So, i am not sure if it is the glare or the duration.

**Comment by matvidako** [comment]
Ok, I managed to reproduce it.

Can you try [this branch](https://github.com/BlinkID/blinkid-ui-android/tree/exp/timeout_test) and see if it works as expected?

If it does, we can make setting timeout value part of the api so you'll be able to increase it, default is 10 seconds.

**Comment by samirpramanik** [comment]
Hi,

The issue is fixed by this commit. Please provide an API for configuring the timeout value.
Also, i have one more doubt :
There is another timeout value where on timeout we show a dialog and prompt user to change document or continue. Its timeout value is : private const val SCAN_TIMEOUT_MILLIS = 16_000L
Could you please explain if this timeout is different and what exactly is the value of 16_000L, because the dialog is definitely not coming after 16 seconds. Now, i understand that subsequent timeouts are doubled, but even the first timeout dialog comes after more than a minute.

**Comment by matvidako** [comment]
Current timeout(SCAN_TIMEOUT_MILLIS) starts as soon as the user opens the screen and is used to remind the user to check the selected document if the scanning isn't working. It restarts when you switch to scanning back side, that could be the reason it isn't showing after 16 seconds.

The timeout I've added in the new branch is set on our SDKs recognizers and is used to tell the SDK when to stop trying to get full results and return partial results.
In BlinkID-UI we just ignore partial results and restart scanning, that is why you were having problems.

**Comment by samirpramanik** [comment]
> It restarts when you switch to scanning back side, that could be the reason it isn't showing after 16 seconds.
- I was referring to the front side itself. I do not see the dialog in 16 seconds. It is taking longer than that exactly 5 minutes.
However, on the app in the playstore, it comes in 16 seconds.

**Comment by samirpramanik** [comment]
I fixed the issue. Actually that timeout was being overridden in my base scan activity. Thanks for your help!
Please provide the API for timeout configuration.

**Comment by samirpramanik** [comment]
Hello, could you please let me know when can i get the API to configure scan timeout.

**Comment by matvidako** [comment]
Hi,

new release is ready, just for you
[v4.8.0.1](https://github.com/BlinkID/blinkid-ui-android/releases/tag/v4.8.0.1)

**Comment by samirpramanik** [comment]
Thanks man! Cheers!
