### ISSUE TITLE
Scan result face image is null

### ISSUE THREAD

**Issue by laoluani** [BlinkID/blinkid-ui-android#44]
Hi, 

I've imported the library as suggested in the readme,  however in the RecognitionResult object returned the faceImage is always null. I've tested this on a UK Driving license and Passport as well as an Irish Passport.

It looks like in the setup method of the BaseRecognition object `therecognizer.setReturnFaceImage(true)` is not called.

Thanks

**Comment by matvidako** [comment]
Hi,

currently, BlinkID-UI will use just Mrtd recognizer for scanning most passports and Mrtd recognizer doesn't support face image. 
This will change in the next release when we'll introduce new Passport recognizer  that will support face image.

UK driving licence uses EUDL recognizer which does support face image, are you sure that you've set the correct document when scanning UK driving licence?

**Comment by laoluani** [comment]
Thanks for the reply.

Do you know when I can expect the next release?

I've previously had issue's scanning my driving license so this may be an unrelated issue.

**Comment by matvidako** [comment]
We don't know the exact date yet but it will most likely be in the next 2 or 3 weeks.

**Comment by laoluani** [comment]
Awesome, Thanks for your help!

**Comment by matvidako** [comment]
Hi,

we've just released a new version that uses passport recognizer.

**Comment by laoluani** [comment]
Awesome thanks for the update. 

Is there plans to publish the blinkId-Ui library on a maven repository?

**Comment by matvidako** [comment]
Hi,

next release will be available through jitpack.
Until then, you can try using snapshot build, like this:
https://jitpack.io/#BlinkID/blinkid-ui-android/jitpack_beta-SNAPSHOT
