### ISSUE TITLE
Can we change the overlay color

### ISSUE THREAD

**Issue by samirpramanik** [BlinkID/blinkid-ui-android#46]
Hi,

Can we change the color of the overlay screen that comes over the recognizer view. As of now, it is a semi-transparent overlay. Can we change it to some custom color?

**Comment by samirpramanik** [comment]
I tried to change `private val overlayColor : Int = ContextCompat.getColor(context, R.color.mbTextScanInstructions)` in **CameraOverlayView.kt**, but still i got a transparent overlay.
Here, mbTextScanInstructions is #FFFFFF

**Comment by matvidako** [comment]
Hi,

CameraOverlayView was moved from BlinkID-UI to BlinkID SDK in v4.7.0.0 which changed color resources used.

So if you're using 4.7.0.0 or later, override: `mb_overlay_camera_translucent`
and if you're using older versions override `mbBgCameraOverlay`.

**Comment by samirpramanik** [comment]
Hi,

I am using the new sdk 4.8.0. Where do i have to override mb_overlay_camera_translucent?
I tried the below in colors.xml - `<color name="mb_overlay_camera_translucent">#ffffffff</color>`
but still the scan area is transparent. If we change mbBgCameraOverlay, the top bar space is changing to white. But the remaining screen is still transparent.

**Comment by samirpramanik** [comment]
Also, if I search mb_overlay_camera_translucent, i find some other entries as well which are generated.
PFB the screenshot.
![search_results](https://user-images.githubusercontent.com/48544382/56129851-59543480-5f94-11e9-9e82-6818e13f0110.PNG)

**Comment by matvidako** [comment]
Hi,

looks like you'll have to override both of these colors.
Here's [a branch](https://github.com/BlinkID/blinkid-ui-android/tree/test/awesome_colors) with updated sample app that overrides them.

To override resource, you just put the resource with the same name in your own resources file (colors.xml for example).

**Comment by samirpramanik** [comment]
Hi Matej,

This fixed the issue. Now we are able to change the overlay color however the frame edges are not perfect. PFA screenshot from our scan screen. Since we have made the background white now, the edges seem to have 1 px gap or some border which does not look good. Can we customize the lines at the edges.
![Screenshot_20190417-082714](https://user-images.githubusercontent.com/48544382/56261477-3472d500-60ec-11e9-9ac1-9cea1f73eaed.png)

**Comment by matvidako** [comment]
Hi,

this is a bug due to how these hooks are drawn. We'll fix it in the next update.

For your use case it might make more sense to completely remove the hooks. You can do that by overriding all hook related dimensions to 0dp.

```
<dimen name="mb_hook_length_vertical">0dp</dimen>
<dimen name="mb_hook_length_horizontal">0dp</dimen>
<dimen name="mb_hook_stroke_width">0dp</dimen>
```

**Comment by samirpramanik** [comment]
Thanks mate!
