### ISSUE TITLE
AndroidX compatibility issue

### ISSUE THREAD

**Issue by laoluani** [BlinkID/blinkid-ui-android#53]
Hey, I am currently using androidX in my project however this library currently does not support it. My workaround has been to fork the project and make the minor changes myself.

Would be great if this was built in, also happy to make a PR.

**Comment by matvidako** [comment]
Hi,

we're planning to switch to androidX soon.
Until then, it should work fine if you [enable jetifier](https://developer.android.com/jetpack/androidx#using_androidx) in your project. Did you have issues even after enabling it?

**Comment by laoluani** [comment]
So I tried this and the mappings to the androidX artifacts cause compilation errors.

1. The androidx.appcompat.app.AppCompatActivity library changed the method signature of onConfigurationChanged(Configuration config) to onConfigurationChanged(@ NonNull Configuration config). Which interops in Kotlin to a non null Configuration type causing compilation errors in the override of your BaseDocumentScanActivity class, which wants a nullable Configuration object. breaking this [line](https://github.com/BlinkID/blinkid-ui-android/blob/bbeeed4e0fcf8d0bcd080c8f96cfde5b86408416/blinkid-ui-lib/src/main/kotlin/com/microblink/documentscanflow/BaseDocumentScanActivity.kt#L397)

2. The androidX counterpart of android.support.design.widget.TabLayout.OnTabSelectedListener no longer inherits from android.support.design.widget.TabLayout.BaseOnTabSelectedListener like it does in the support library. As seen [here](https://github.com/material-components/material-components-android/blob/c045cca69dc8cb7f92d715b2c15daa56546a85bd/lib/java/com/google/android/material/tabs/TabLayout.java#L345), breaking this [line](https://github.com/BlinkID/blinkid-ui-android/blob/bbeeed4e0fcf8d0bcd080c8f96cfde5b86408416/blinkid-ui-lib/src/main/kotlin/com/microblink/documentscanflow/BaseDocumentScanActivity.kt#L296).

The simple fix for 1. was to change the method signature of your BaseDocumentScanActivity override from onConfigurationChanged(Configuration? config) to onConfigurationChanged(Configuration config). The fix for 2. was to create a lambda using the BaseOnTabSelectedListener rather than OnTabSelectedListener.

**Comment by matvidako** [comment]
Thanks, we'll include those 2 fixes in the next release to make sure everything works for both androidX and support lib users.

**Comment by laoluani** [comment]
Awesome looking forward to it and thanks for the speedy replies!

**Comment by matvidako** [comment]
Hi, 

we've just released a new version that includes AndroidX fixes.
