### ISSUE TITLE
V4.10.0 available in Blink ID

### ISSUE THREAD

**Issue by rajubhusani** [BlinkID/blinkid-ui-android#56]
Team,

Can we use the latest SDK V4.10.0 with the existing BlinkUI SDK? Or do we need to do any changes on the UI library? As I'm facing the errors while updating the Blink ID library.

**Comment by matvidako** [comment]
Hi,

we've just released a new version that works with BlinkID 4.10.0 
https://github.com/BlinkID/blinkid-ui-android/releases/tag/v4.10.0.0

**Comment by rajubhusani** [comment]
Hi,

Thanks for the update.

Currently we are focusing on only one country ID scan, Is it possible that BlinkID.aar which is referring from Maven can use only one country. Because when building the .apk the size is increasing up to 20MB more. We would like to change that size of apk.

Can you suggest on this?

**Comment by matvidako** [comment]
Simplest solution would be to use apk splits as described [here](https://github.com/BlinkID/blinkid-android#-reducing-the-final-size-of-your-app). This should considerably reduce the size of your apks.

If that isn't good enough, please contact us at support@microblink.com for instructions on how to make BlinkID aar that only includes recognizers you need to use (so called min size build).

Unfortunately, min size build won't work with BlinkID UI without changes. You could fork BlinkID UI, change its BlinkID dependency to your min size aar and delete all code that fails to compile.
or alternatively, you could use only BlinkID SDK and include parts of BlinkID UI code in your app.

**Comment by rajubhusani** [comment]
Thanks a lot. I will close the ticket now.
