### ISSUE TITLE
Change overlay color

### ISSUE THREAD

**Issue by samirpramanik** [BlinkID/blinkid-ui-android#59]
Hi,

Can we change the overlay used in **DocumentOverlayController** to some desired color. As of now, it is a semi-transparent screen. How do we customize it? 
Also, can we disable the scan frame rotation when we rotate the device from portrait to landscape? I tried `uiSettings = new DocumentUISettings(intent);
uiSettings.setRegionOfInterestRotatable(false); ` but `uiSettings.getRegionOfInterestRotatable();` already return false.

**Comment by samirpramanik** [comment]
Hi,

I figured out the forced orientation using `uiSettings.setForcedOrientation(OverlayOrientation.PORTRAIT);`
Please help with the overlay color.

**Comment by matvidako** [comment]
Hi,

You can override the overlay by creating your own drawable named `mb_gradient_overlay`.
