### ISSUE TITLE
Can we pick a document stored in the same device

### ISSUE THREAD

**Issue by samirpramanik** [BlinkID/blinkid-ui-android#65]
Hello,

Was just wondering if we can pick documents stored in the same phone where we have the Blink ID application and scan them as well?

**Comment by matvidako** [comment]
Hi,

this use case is not included in BlinkID UI but BlinkID does support this, you can do recognition directly on a bitmap,  check the [direct api sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-DirectApiSample/src/main/java/com/microblink/blinkid/imagescan/ScanImageActivity.java) to see how to do this.

**Comment by Brankacro** [comment]
Hello,

we are solving this issue, in case of any questions or doubts, please reopen it and we will gladly help you.
Kind regards.

Branka
