### ISSUE TITLE
Get Date of  issue on Passport

### ISSUE THREAD

**Issue by dannijax** [BlinkID/blinkid-ui-android#75]
I'm Using blinkid-ui-android to scan International passport but i don't get the date of issue in the result.
How can I get the date of issue form Int' Passport

**Comment by eddieAvdg** [comment]
Hi @dannijax 

For the purposes of scanning passports, our SDK reads data from the MRZ which does not contain the date of issue.
According to the ICAO standard, the only dates contained in the MRZ are date of birth and date of expiry.
For more information, please take a look at our FAQ page, specifically:
https://help.microblink.com/hc/en-us/articles/360007487833-MRTD-FAQ

Best regards,
Edhem

**Comment by eddieAvdg** [comment]
On the other hand, there might be a workaround for the issue.
If you know which passports you are scanning, or rather if you know how long they are valid after being issued, you could calculate the date of issue based on the date of expiry.
That, again, would just be a workaround and might not be applicable in all cases.

**Comment by dannijax** [comment]
thanks for the response @eddieMicroblink
